os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y ack-grep cmake cpanminus docbook-defguide docbook-xsl docbook-xsl-ns hunspell mercurial myspell-en-gb libhunspell-dev libperl-dev perl python3 python3-setuptools python3-pip valgrind wml xsltproc
    - sudo -H `which python3` -m pip install cookiecutter
    - sudo dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
    - sudo cpanm --notest Alien::Tidyp App::XML::DocBook::Builder Pod::Xhtml YAML::XS
    - sudo cpanm --notest HTML::Tidy
    - "sudo cpanm --notest $(perl -MYAML::XS=LoadFile -e 'print join q( ), sort {$a cmp $b} keys(%{LoadFile(q(bin/required-modules.yml))->{required}->{perl5_modules}})')"
    - gem install sass compass compass-blueprint
    - a='latemp' ; v='0.8.0' ; b="$a-$v" ; arc="$b.tar.xz"; ( cd .. && wget http://web-cpan.shlomifish.org/latemp/download/"$arc" && tar -xvf "$arc" && cd "$b" && mkdir b && cd b && cmake .. && make && sudo make install)
    - ( hg clone https://shlomif@bitbucket.org/shlomif/wml-extended-apis && cd wml-extended-apis/xhtml/1.x && bash Install.bash )
    - ( hg clone https://shlomif@bitbucket.org/shlomif/wml-affiliations && cd wml-affiliations/wml && bash Install.bash )
    - ( cd .. && hg clone https://shlomif@bitbucket.org/shlomif/latemp && cd latemp/support-headers && perl install.pl )
script: "m() { make DOCBOOK5_XSL_STYLESHEETS_PATH=/usr/share/xml/docbook/stylesheet/docbook-xsl-ns \"$@\" ; } ; export SKIP_SPELL_CHECK=1; ./gen-helpers.pl && m && m test"
